version: '3'
volumes:
  redis-data:
    driver: local
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config/config.yml:/app/config/config.yml
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - redis
    environment:
      - PORT=${PORT}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  redis:
    image: redis:6.2-alpine
    volumes:
      - redis-data:/data