bots:
  caythueelo_telegram_bot:
    type: 'TELEGRAM'
    token: '--'
    chat_chanel_id: '222'
    conditions:
      content_regex: '.*?'
      account_regex: '.*?'
  caythueelo_discord_bot:
    type: 'DISCORD'
    token: '--'
    chat_chanel_id: '111'
    conditions:
      content_regex: '.*?'
      account_regex: '.*?'
webhooks:
  caythueelo_webhook:
    url: 'https://caythueelo.com/api/payment/callback'
    token: '123456789:ABCDEF'
    conditions:
      content_regex: '.*?'
      account_regex: '^456$'

gateways:
  mb_bank_1:
    type: 'MBBANK'
    password: '--'
    account: '456'
    token: '`'
    repeat_interval_in_sec: 10
  abc_bank_1:
    type: 'ACBBANK'
    password: '--'
    account: '123'
    token: '`'
    repeat_interval_in_sec: 10
